import type { AppProps } from "next/app";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { appWithI18Next } from "ni18n";
import { ni18nConfig } from "../../next-i18next.config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ Component, pageProps }: AppProps) {
  return (
    <html lang="vi">
      <body className={inter.className}>
        <StoreProvider>
          <Component {...pageProps} />
        </StoreProvider>
      </body>
    </html>
  );
}

export default appWithI18Next(RootLayout, ni18nConfig);
